framework:
    messenger:
        transports:
            sync: 'sync://'
            async: "enqueue://sqs?topic[name]=test&queue[name]=test&receiveTimeout=3"
        routing:
            'App\Store\Shared\Application\TestMessage': async