version:  '3.7'

services:
  nginx:
    container_name: container_nginx
    build:
      context: docker/nginx
      args:
        MAX_EXECUTION_TIME: ${MAX_EXECUTION_TIME}
        SERVER_NAME: ${SERVER_NAME}
    ports:
      - "80:80"
    volumes:
      - nginx:/var/log/nginx
    depends_on:
      - php

  mysql:
    container_name: mysql_mytheresa_store
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  php:
    container_name: php_mytheresa
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - type: bind
        source: ../mytheresa-store
        target: /var/www/symfony
      - type: volume
        source: php
        target: /var/www/symfony/var/log
    restart: on-failure
    env_file:
      - .env
    user: 0:0
    command: bash -c "php -d memory_limit=256M /usr/bin/composer install && php bin/console doctrine:database:drop && php bin/console doctrine:database:create && php bin/console doctrine:schema:create && php bin/console doctrine:schema:update --force"

volumes:
  mysql:
  nginx:
  php: