App\Store\Discounts\Domain\Discount:
  type: entity
  table: discount
  id:
    id:
      type: DiscountId

  embedded:
    percentage:
      class: App\Store\Discounts\Domain\Percentage
      columnPrefix: percentage_

