App\Store\Categories\Domain\Category:
  type: entity
  table: category
  id:
    id:
      type: CategoryId

  embedded:
    name:
      class: App\Store\Categories\Domain\CategoryName
      columnPrefix: name_

  manyToOne:
    discount:
      targetEntity: App\Store\Discounts\Domain\Discount
      joinColumn:
        name: discount_id
        referencedColumnName: id
