services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\Store\Categories\Domain\Category\DiscountRepositoryInterface: '@App\Store\Shared\Infrastructure\Persistence\DoctrineDiscountRepositoryInterface'
  App\Store\Shared\Infrastructure\Persistence\DoctrineDiscountRepositoryInterface:
    arguments:
      - '@doctrine.orm.default_entity_manager'